<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>LiteDB.Spatial</RootNamespace>
    <AssemblyName>LiteDB.Spatial.Cartesian2D</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1701;1702;1705;1591;0618</NoWarn>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\LiteDB.Spatial.Cartesian2D.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiteDB.Spatial.Core\LiteDB.Spatial.Core.csproj" />
    <ProjectReference Include="..\LiteDB\LiteDB.csproj">
      <Aliases>LiteDbBase</Aliases>
    </ProjectReference>
  </ItemGroup>

</Project>
