#nullable enable

using System;

namespace LiteDB.Spatial;

/// <summary>
/// Provides helpers for inspecting spatial query plans.
/// </summary>
public static class SpatialDiagnostics
{
    /// <summary>
    /// Creates an explain result for the supplied plan.
    /// </summary>
    /// <param name="plan">The spatial plan generated by an engine.</param>
    /// <param name="descriptor">Optional collection descriptor that enriches diagnostics with field metadata.</param>
    /// <returns>A <see cref="SpatialExplainResult"/> describing the plan.</returns>
    public static SpatialExplainResult Explain(ISpatialQueryPlan plan, SpatialCollectionDescriptor? descriptor = null)
    {
        if (plan == null)
        {
            throw new ArgumentNullException(nameof(plan));
        }

        return new SpatialExplainResult(
            plan.EngineName,
            plan.Dimensions,
            plan.CoveringBounds,
            plan.IndexRanges,
            plan.ExactPredicateDescription,
            plan.Covering,
            descriptor?.Options.IndexFieldName,
            descriptor?.Options.BoundingBoxFieldName);
    }
}
