name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore LiteDB.sln

      - name: Build
        run: dotnet build LiteDB.sln --configuration Release --no-restore /p:DefineConstants=TESTING

      - name: Test
        timeout-minutes: 3
        run: dotnet test LiteDB.sln --configuration Release --no-build --verbosity normal --settings tests.ci.runsettings --logger "trx;LogFileName=TestResults.trx" --logger "console;verbosity=detailed" /p:DefineConstants=TESTING

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: "**/*TestResults*.trx"
